@startuml Figure_9.2
left to right direction

object "__firstFloor : Floor__" as firstFloor
object "__kitchen : Space__" as kitchen
object "__: WallOpening__" as WallOpening
object "__lunchRoom : Space__" as lunchRoom

firstFloor --> kitchen
firstFloor --> lunchRoom

kitchen -> WallOpening
kitchen <- WallOpening
WallOpening <- lunchRoom
WallOpening -> lunchRoom

object "__: window__" as window0
object "__: window__" as window1
object "__outside : Space__" as outside

kitchen   --> window0
lunchRoom --> window1

window0 -> outside
outside <- window1

object "__: Door__" as Door

lunchRoom -> Door
lunchRoom <- Door

Door --> outside
Door "opensInto" --> outside
@enduml