@startuml Figure_1.2
' TreeMap_ClassDiagram
class TreeMap{
    + add(key, value)
    + get(key)
}

class TreeMapNode{
    + add(key, value)
    + find(key)
}

interface Comparable <<interface>> {

}

object Object

' ->  : horizontal
' --> : vertical
TreeMap -> "topNode" TreeMapNode

TreeMapNode --> "2, nodes" TreeMapNode

TreeMapNode --> "itsValue" Object
TreeMapNode --> "itsKey"   Comparable

@enduml