@startuml Figure_1.5
' TreeMap_CollaborationDiagram

actor Actor
rectangle "<u>:TreeMap</u>" as TreeMap
rectangle "<u>topNode</u>\n<u>:TreeMapNode</u>" as topNode

Actor   -> TreeMap   : "1: add(key, value)\n<size:24><&arrow-right></size>"
TreeMap -->  topNode : "<size:24><&arrow-bottom></size>[topNode != null]\n\t1.1: add(key, vaule)"

'Others icons
' 사용 가능한 모든 아이콘은 아래 URL에서 확인 가능하다.
' https://github.com/plantuml/plantuml/blob/bc1074a7758e80c523aa51c4665fc23949827980/src/net/sourceforge/plantuml/openiconic/data/all.txt
'<&arrow-left>
'<&arrow-right>
'<&arrow-top>
'<&arrow-bottom>
'<&loop-circular>
@enduml