@startuml Figure_1.4
' TreeMap_SequenceDiagram

actor Actor
participant "<u>:TreeMap</u>" as map

Actor -> map : add(key, value)
activate map

create "<u>topNode:</u>\n<u>TreeMapNode</u>" as node
map -> node : value key\no->     o->\n[topNode == null]
map -> node : add(key,value)\n[topNode != null]
note left
두 Sequence가 한 점에서 출발하도록
하는 것은 불가능하다
endnote

' activeate
' deactivate
' destroy

@enduml