@startuml Figure_2.4

' Line을 모두 직각으로 그린다.
'skinparam linetype ortho
skinparam linetype PolyLine
skinparam groupinheritance 2


class "Geometric Object"
class "Point"
class "LinearObject"
class "Ray"
class "InifiniteLine"
class "Line"
class "PolyLine"

"Geometric Object" <|-- "LinearObject"
"Geometric Object" <|-- "Point"
"Point" "2" <- "LinearObject"
"LinearObject" <|-- "Ray"
"LinearObject" <|-- "InifiniteLine"
"LinearObject" <|-- "Line"
"PolyLine" --> "*" "Line"

class "Space"
class "Portal"
class "Authored Space"
class "Human Portal"
class "Window"
class "Door"
class "WallOpening"

"PolyLine" "itsOutline" <- "Space"
"Space" -> "Authored Space"
"Space" --> "Portal"
"Space" "2" <-- "Portal"
"Portal" <|-- "Human Portal"
"Portal" <|-- "Window"
"Human Portal" <|-- "Door"
"Human Portal" <|-- "WallOpening"

@enduml