@startuml Figure_2.1

class "User Database"{
    + getUser()
}

class "Login Servlet" {
    + processRequest()
}

interface Servlet <<interface>> {

}

class HTTPRequest
class HTTPResponse

Servlet <|-- "Login Servlet"
"User Database" <- "Login Servlet"

Servlet -> HTTPRequest
(Servlet, HTTPRequest) --> HTTPResponse

@enduml